### ISSUE TITLE
use allow filtering

### ISSUE THREAD

**Issue by justinjoseph89** [wjch-krl/pgCassandra#2]
Hi,
I have multiple primary key fields in Cassandra. And i need to apply WHERE condition on one of those filed then i am getting the following error,

`code=2200 [Invalid query] message=\"Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING`

What will be the possible reason?

**Comment by wjch-krl** [comment]
It have been fixed in my last commit.

The reason of the error was that cassandra don't allow filtering on all primary key columns in every case ([http://stackoverflow.com/questions/17735825/query-using-composite-keys-other-than-row-key-in-cassandra](url)). And I have forgotten about this specific case

**Comment by ratheesh-kr** [comment]
So, If we are using the latest code, The allow Filtering will work. right?

**Comment by wjch-krl** [comment]
Yes, It should

**Comment by ratheesh-kr** [comment]
Thank you very much for your help.
